export const fakeStudent = {
  columns: [
    {
      title: "Name",
      dataIndex: "name",
      key: "name",
    },
    {
      title: "Matric No",
      dataIndex: "matric",
      key: "matric",
    },
    {
      title: "Sex",
      dataIndex: "sex",
      key: "sex",
    },
    {
      title: "Age",
      dataIndex: "age",
      key: "age",
    },
    {
      title: "CGPA",
      dataIndex: "cgpa",
      key: "cgpa",
    },
    {
      title: "Email",
      dataIndex: "email",
      key: "email",
    },
  ],
  data: [
    {
      name: "Daniel Regna",
      matric: "Pro2219",
      sex: "Female",
      age: 20,
      cgpa: 3.14,
      email: "idontknow@pro.com",
      dob: "2 May, 2002",
      level: "300 Level",
      img: "https://i.pravatar.cc/150?img=28",
    },
    {
      name: "Daniel Regna",
      matric: "Pro2219",
      sex: "Female",
      age: 20,
      cgpa: 3.14,
      email: "idontknow@pro.com",
      dob: "2 May, 2002",
      level: "300 Level",
      img: "https://i.pravatar.cc/150?img=28",
    },
    {
      name: "Daniel Regna",
      matric: "Pro2219",
      sex: "Female",
      age: 20,
      cgpa: 3.14,
      email: "idontknow@pro.com",
      dob: "2 May, 2002",
      level: "300 Level",
      img: "https://i.pravatar.cc/150?img=28",
    },
    {
      name: "Daniel Regna",
      matric: "Pro2219",
      sex: "Female",
      age: 20,
      cgpa: 3.14,
      email: "idontknow@pro.com",
      dob: "2 May, 2002",
      level: "300 Level",
      img: "https://i.pravatar.cc/150?img=28",
    },
    {
      name: "Daniel Regna",
      matric: "Pro2219",
      sex: "Female",
      age: 20,
      cgpa: 3.14,
      email: "idontknow@pro.com",
      dob: "2 May, 2002",
      level: "300 Level",
      img: "https://i.pravatar.cc/150?img=28",
    },
    {
      name: "Daniel Regna",
      matric: "Pro2219",
      sex: "Female",
      age: 20,
      cgpa: 3.14,
      email: "idontknow@pro.com",
      dob: "2 May, 2002",
      level: "300 Level",
      img: "https://i.pravatar.cc/150?img=28",
    },
    {
      name: "Daniel Regna",
      matric: "Pro2219",
      sex: "Female",
      age: 20,
      cgpa: 3.14,
      email: "idontknow@pro.com",
      dob: "2 May, 2002",
      level: "300 Level",
      img: "https://i.pravatar.cc/150?img=28",
    },
    {
      name: "Daniel Regna",
      matric: "Pro2219",
      sex: "Female",
      age: 20,
      cgpa: 3.14,
      email: "idontknow@pro.com",
      dob: "2 May, 2002",
      level: "300 Level",
      img: "https://i.pravatar.cc/150?img=28",
    },
    {
      name: "Daniel Regna",
      matric: "Pro2219",
      sex: "Female",
      age: 20,
      cgpa: 3.14,
      email: "idontknow@pro.com",
      dob: "2 May, 2002",
      level: "300 Level",
      img: "https://i.pravatar.cc/150?img=28",
    },
    {
      name: "Daniel Regna",
      matric: "Pro2219",
      sex: "Female",
      age: 20,
      cgpa: 3.14,
      email: "idontknow@pro.com",
      dob: "2 May, 2002",
      level: "300 Level",
      img: "https://i.pravatar.cc/150?img=28",
    },
    {
      name: "Daniel Regna",
      matric: "Pro2219",
      sex: "Female",
      age: 20,
      cgpa: 3.14,
      email: "idontknow@pro.com",
      dob: "2 May, 2002",
      level: "300 Level",
      img: "https://i.pravatar.cc/150?img=28",
    },
    {
      name: "Daniel Regna",
      matric: "Pro2219",
      sex: "Female",
      age: 20,
      cgpa: 3.14,
      email: "idontknow@pro.com",
      dob: "2 May, 2002",
      level: "300 Level",
      img: "https://i.pravatar.cc/150?img=28",
    },
  ],
};
